[tool.poetry]
name = "pysmallerwebhexagon"
version = "0.1.0"
description = "ğŸ›‘ Illustration of a simple hexagon architeture app in Python ğŸ"
authors = ["cassiobotaro <cassiobotaro@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
starlette = {extras = ["httpx", "jinja2"], version = "^0.37.2"}
jinja2 = "^3.1.4"
httpx = "^0.27.0"
uvicorn = "^0.30.1"
fastapi = "^0.111.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
